## publish on dockerhub, ryanrek007/angular:latest
FROM node:14.18.0-alpine3.14
LABEL "Install node.js and angular base"="customize version by Ryan"

## create dependency angular cli
RUN npm install -g @angular/cli@12.2.9
