version: "3.7"

services:
  nginx:
    # build:  #Ngebuild image dari file Dockerfile pada directory yang sama, jika belum pull dari docker registry/dockerhub
    #   context: ./
    #   dockerfile: Dockerfile
    #
    image: ryanrek007/nginx-debian-webserver:1.5
    container_name: nginx-service-test
    restart: always
    working_dir: /etc/nginx
    volumes: 
      - ./nginx:/etc/nginx/conf.d/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - 3005:80
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks: 
      - nginx-lab
 
networks: 
  nginx-lab:
    name: nginx-lab
